package ch.items.enums;

public enum Material {

	GRANITE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1),
	POLISHED_GRANITE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, Material.GRANITE, Material.GRANITE, Material.GRANITE, Material.GRANITE),
	DIORITE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1),
	POLISHED_DIORITE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, DIORITE, Material.DIORITE, Material.DIORITE, Material.DIORITE),
	ANDESITE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1 ),
	POLISHED_ANDESITE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, Material.ANDESITE, Material.ANDESITE, Material.ANDESITE, Material.ANDESITE),
	GRASSBLOCK(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1),
	DIRT(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	PODZOL(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1),
	COBBLESTONE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1),
	STONE(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.BLOCKS, 1, Material.COBBLESTONE),
	OAK_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	SPRUCE_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	BIRCH_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	JUNGLE_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	ACACIA_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	DARK_OAK_SAPLING(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD, 1),
	SAND(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	RED_SAND(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	GRAVEL(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	COARSE_DIRT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, Material.DIRT, Material.GRAVEL, Material.DIRT, Material.GRAVEL),
	GOLD_ORE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	IRON_ORE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	COAL_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.ORES,1),
	OAK_WOOD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	SPRUCE_WOOD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	BIRCH_WOOD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	JUNGLE_WOOD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	RANDOM_WOOD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	OAK_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.OAK_WOOD),
	SPRUCE_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.SPRUCE_WOOD),
	BIRCH_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.BIRCH_WOOD),
	JUNGLE_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.JUNGLE_WOOD),
	RANDOM_WOOK_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.RANDOM_WOOD),
	OAK_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	SPRUCE_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	BIRCH_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	JUNGLE_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	SPONGE(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	WET_SPONGE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1, Material.SPONGE),
	GLASS(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.COLORED, 1, Material.SAND),
	LAPIS_LAZULI_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.ORES,1),
	SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, SAND, SAND, SAND, SAND),
	SMOOTH_SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, SANDSTONE, SANDSTONE, SANDSTONE, SANDSTONE),
	COBWEB(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.OTHER,1),
	TALLGRASS(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	FERN(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	DEAD_BUSH(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	DANDELION(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	POPPY(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	BLUE_ORCHID(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	ALLIUM(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	AZURE_BLUET(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	RED_TULIP(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	ORANGE_TULIP(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	WHITE_TULIP(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	PINK_TULIP(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	OXEYE_DAISY(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	MUSHROOM_BROWN(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH,1),
	MUSHROOM_RED(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH,1),
	STONE_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, STONE,  STONE, STONE),
	SANDSTONE_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, SANDSTONE, SANDSTONE, SANDSTONE),
	CHISELED_SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, SANDSTONE_SLAB, SANDSTONE_SLAB),
	COBBLESTONE_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, COBBLESTONE, COBBLESTONE, COBBLESTONE),
	OBSIDIAN(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS,1),
	OAK_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS),
	CHEST(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS, Material.OAK_WOOD_PLANKS),
	DIAMOND_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.ORES,1),
	CRAFTING_TABLE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS),
	FURNACE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE),
	COBBLESTONE_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE),
	STONE_PRESSURE_PLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 1, STONE, STONE),
	WOODEN_PRESSURE_PLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1,  OAK_WOOD_PLANKS, OAK_WOOD_PLANKS),
	REDSTONE_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.ORES,1),
	STONE_BUTTON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 1, STONE),
	ICE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH,1),
	CACTUS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	PUMPKIN(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	NETHERRACK(RecuperationType.MINE, SectionsType.NETHER, SubSection.BLOCKS,1),
	SOUL_SAND(RecuperationType.MINE, SectionsType.NETHER, SubSection.BLOCKS,1),
	WOODEN_TRAPDOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 2, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS),
	STONE_BRICKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, STONE, STONE, STONE, STONE),
	STONE_BRICKS_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, STONE_BRICKS, STONE_BRICKS, STONE_BRICKS),
	CRACKED_STONE_BRICKS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1, STONE_BRICKS),
	CHISELED_STONE_BRICKS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.BLOCKS, 1, STONE_BRICKS_SLAB, STONE_BRICKS_SLAB),
	BROWN_MUSHROOM_BLOCK(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH, 1),
	RED_MUSHROOM_BLOCK(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH, 1),
	GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS ),
	VINES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	MOSSY_STONE_BRICKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, STONE_BRICKS, VINES),
	MOSSY_COBBLESTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, Material.VINES, Material.COBBLESTONE),
	STONE_BRICKS_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, STONE_BRICKS,STONE_BRICKS,STONE_BRICKS,STONE_BRICKS,STONE_BRICKS,STONE_BRICKS),
	MYCELIUM(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH, 1),
	LILY_PAD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	END_STONE(RecuperationType.MINE, SectionsType.END, SubSection.BLOCKS,1),
	DRAGON_EGG(RecuperationType.DROP_MOB, SectionsType.END, SubSection.BLOCKS,1),
	OAK_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS),
	SPRUCE_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS),
	BIRCH_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS),
	JUNGLE_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS),
	SANDSTONE_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,4, SANDSTONE, SANDSTONE, SANDSTONE, SANDSTONE, SANDSTONE, SANDSTONE),
	EMERALD_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH,1),
	SPRUCE_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS, SPRUCE_WOOD_PLANKS),
	BIRCH_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS , Material.BIRCH_WOOD_PLANKS),
	JUNGLE_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS, JUNGLE_WOOD_PLANKS),
	COBBLESTONE_WALL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,6, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE),
	MOSSY_COBBLESTONE_WALL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,6, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE),
	WOODEN_BUTTON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.OAK_WOOD_PLANKS),
	RANDOM_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 6, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	NETHER_QUARTZ_ORE(RecuperationType.MINE_SILK_TOUCH, SectionsType.NETHER, SubSection.SILK_TOUCH,1),
	ACACIA_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	DARK_OAK_LEAVES(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	ACACIA_WOOD(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	DARK_OAK_WOOD(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.WOOD,1),
	ACACIA_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.ACACIA_WOOD),
	DARK_OAK_WOOD_PLANKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 4, Material.DARK_OAK_WOOD),
	ACACIA_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, ACACIA_WOOD_PLANKS, ACACIA_WOOD_PLANKS, ACACIA_WOOD_PLANKS),
	DARK_OAK_WOOD_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,6, DARK_OAK_WOOD_PLANKS, DARK_OAK_WOOD_PLANKS, DARK_OAK_WOOD_PLANKS),
	ACACIA_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS),
	DARK_OAK_WOOD_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS),
	SLIME_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.MOBS_DROPS,1),
	IRON_TRAPDOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1),
	PACKED_ICE(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SILK_TOUCH,1),
	SUNFLOWER(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	LILAC(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	DOUBLE_TALLGRASS(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	LARGE_FERN(RecuperationType.MINE_SHEARS, SectionsType.OVER_WORLD, SubSection.SHEARS,1),
	ROSE_BUSH(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	PEONY(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	RED_SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, Material.RED_SAND, Material.RED_SAND, Material.RED_SAND, Material.RED_SAND),
	SMOOTH_RED_SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,4, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE),
	RED_SANDSTONE_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,4, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE),
	RED_SANDSTONE_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,6, Material.RED_SANDSTONE, Material.RED_SANDSTONE, Material.RED_SANDSTONE),
	CHISELED_RED_SANDSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, Material.RED_SANDSTONE_SLAB, Material.RED_SANDSTONE_SLAB),
	APPLE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COAL(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	COAL_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,1, Material.COAL, Material.COAL, Material.COAL, Material.COAL, Material.COAL, Material.COAL, Material.COAL, Material.COAL, Material.COAL),
	CHARCOAL(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.ORES,1, Material.RANDOM_WOOD),
	DIAMOND(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	JUKEBOX(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, DIAMOND, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS),
	DIAMOND_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES, 1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND),
	GOLD_INGOT(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.ORES,1, Material.GOLD_ORE),
	GOLD_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES, 1, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT),
	LIGHT_WEIGHTED_PRESSURE_PLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.GOLD_INGOT, Material.GOLD_INGOT),
	STICK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	IRON_INGOT(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.ORES,1, Material.IRON_ORE),
	IRON_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES, 1, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT),
	IRON_SWORD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.STICK),
	WOODEN_SWORD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.STICK),
	WOODEN_SHOVEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.RANDOM_WOOK_PLANKS, Material.STICK),
	WOODEN_PICKAXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1 , Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.STICK, Material.STICK),
	WOODEN_AXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.STICK, Material.STICK),
	STONE_SWORD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.COBBLESTONE, Material.COBBLESTONE, Material.STICK),
	STONE_SHOVEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.COBBLESTONE, Material.STICK, Material.STICK),
	STONE_PICKAXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.STICK, Material.STICK),
	STONE_AXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.STICK, Material.STICK),
	DIAMOND_SWORD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.DIAMOND, Material.DIAMOND, Material.STICK),
	DIAMOND_SHOVEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.DIAMOND, Material.STICK, Material.STICK),
	DIAMOND_PICKAXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.STICK, Material.STICK),
	DIAMOND_AXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.STICK, Material.STICK),
	ANVIL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, Material.IRON_BLOCK, Material.IRON_BLOCK, Material.IRON_BLOCK, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	SLIGHTLY_DAMAGED_ANVIL(RecuperationType.USE, SectionsType.OTHER, SubSection.BLOCKS,1, Material.ANVIL),
	VERY_DAMAGED_ANVIL(RecuperationType.USE, SectionsType.OTHER, SubSection.BLOCKS,1, Material.ANVIL),
	HEAVY_WEIGHTED_PRESSURE_PLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.IRON_INGOT, Material.IRON_INGOT),
	IRON_BAR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,16, IRON_INGOT,IRON_INGOT,IRON_INGOT,IRON_INGOT,IRON_INGOT,IRON_INGOT),
	TRIPWIRE_HOOK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,2, IRON_INGOT, STICK, RANDOM_WOOK_PLANKS),
	TRAPPED_CHEST(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1 , Material.CHEST, Material.TRIPWIRE_HOOK),
	HOPPER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.CHEST, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	IRON_SHOVEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.STICK, Material.STICK),
	IRON_PICKAXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.STICK, Material.STICK),
	IRON_AXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.STICK, Material.STICK),
	SPRUCE_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	BIRCH_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	JUNGLE_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	DARK_OAK_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	ACACIA_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	SPRUCE_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.STICK, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS),
	BIRCH_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.STICK, Material.BIRCH_WOOD_PLANKS,Material.BIRCH_WOOD_PLANKS,Material.BIRCH_WOOD_PLANKS,Material.BIRCH_WOOD_PLANKS),
	JUNGLE_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.STICK, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS),
	DARK_OAK_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.STICK, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS),
	ACACIA_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.STICK, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS),
	OAK_FENCE_GATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, STICK, STICK, STICK, STICK, OAK_WOOD_PLANKS),
	OAK_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3 , OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, OAK_WOOD_PLANKS, STICK, STICK),
	LEVER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, STICK, COBBLESTONE),
	RAILS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 16, Material.IRON_INGOT , Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, STICK),
	LADDER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3 , STICK, STICK, STICK, STICK, STICK, STICK, STICK),
	TORCH(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 4, Material.COAL, Material.STICK),
	PUMPKIN_LANTERN(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.VEGETAL,1, PUMPKIN, TORCH),
	BOWL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,4, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	SOUP(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.MUSHROOM_BROWN, Material.MUSHROOM_RED, Material.BOWL),
	GOLDEN_SWORD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.STICK),
	GOLDEN_SHOVEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.GOLD_INGOT, Material.STICK, Material.STICK),
	GOLDEN_PICKAXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.STICK, Material.STICK),
	GOLDEN_AXE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.STICK, Material.STICK),
	STRING(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	BOW(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STRING, Material.STRING, Material.STRING, Material.STICK),
	WOOL(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.COLORED, 1, STRING, STRING, STRING, STRING),
	FEATHER(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	GUNPOWDER(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	TNT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, GUNPOWDER, GUNPOWDER, GUNPOWDER, GUNPOWDER, GUNPOWDER, SAND, SAND, SAND, SAND),
	WOODEN_HOE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.STICK, Material.STICK),
	STONE_HOE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STICK, Material.STICK, Material.COBBLESTONE, Material.COBBLESTONE),
	IRON_HOE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STICK, Material.STICK, Material.IRON_INGOT, Material.IRON_INGOT),
	DIAMOND_HOE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STICK, Material.STICK, Material.DIAMOND, Material.DIAMOND),
	GOLDEN_HOE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STICK, Material.STICK, Material.GOLD_INGOT, Material.GOLD_INGOT),
	SEEDS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	WHEAT(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	HAY_BALE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.WHEAT),
	BREAD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.WHEAT, Material.WHEAT, Material.WHEAT),
	CHAINMAIL_HELMET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1),
	CHAINMAIL_CHESTPLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1),
	CHAINMAIL_LEGGINGS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1),
	CHAINMAIL_BOOTS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1),
	IRON_HELMET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	IRON_CHESTPLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	IRON_LEGGINGS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	IRON_BOOTS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	DIAMOND_HELMET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND),
	DIAMOND_CHESTPLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND),
	DIAMOND_LEGGINGS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND),
	DIAMOND_BOOTS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND, Material.DIAMOND),
	GOLDEN_HELMET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT),
	GOLDEN_CHESTPLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT),
	GOLDEN_LEGGINGS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT),
	GOLDEN_BOOTS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT),
	FLINT(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.OTHER,1),
	FLINT_AND_STEEL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.FLINT),
	ARROW(RecuperationType.DROP_MOB, SectionsType.OTHER, SubSection.OTHER,1, Material.FLINT, Material.STICK, Material.FEATHER),
	PORKCHOP(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_PORKCHOP(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.FOOD,1, Material.PORKCHOP),
	PAINTING(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.WOOL, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	GOLDEN_APPLE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.APPLE, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT),
	GOLDEN_APPLE_CHEAT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.APPLE, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK, Material.GOLD_BLOCK),
	SIGN(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,3, Material.STICK, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	WOODEN_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	BUCKET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	WATER_BUCKET(RecuperationType.WATER, SectionsType.OVER_WORLD, SubSection.OTHER,1, Material.BUCKET),
	LAVA_BUCKET(RecuperationType.LAVA, SectionsType.OVER_WORLD, SubSection.OTHER,1, Material.BUCKET),
	MINECART(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	SADDLE(RecuperationType.DUNGEON, SectionsType.OTHER, SubSection.LUCK,1),
	IRON_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	REDSTONE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	DROPPER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE, Material.REDSTONE),
	REDSTONE_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,1, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE, Material.REDSTONE),
	REDSTONE_TORCH(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 1, STICK, REDSTONE),
	ACTIVATOR_RAILS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,6, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.STICK, Material.STICK, Material.REDSTONE_TORCH),
	PISTON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 1, REDSTONE, IRON_INGOT, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS),
	POWERED_RAILS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 6, REDSTONE, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, GOLD_INGOT, STICK),
	DETECTOR_RAILS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 6, REDSTONE, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT),
	NOTE_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, RANDOM_WOOK_PLANKS, REDSTONE),
	DISPENSER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, REDSTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, BOW),
	SNOWBALL(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	SNOW_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, SNOWBALL, SNOWBALL, SNOWBALL, SNOWBALL),
	SNOW_LAYER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, SNOW_BLOCK, SNOW_BLOCK, SNOW_BLOCK),
	BOAT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD,1, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	LEATHER(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	LEATHER_HELMET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER),
	LEATHER_CHESTPLATE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER),
	LEATHER_LEGGINGS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER),
	LEATHER_BOOTS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ARMORS,1, Material.LEATHER, Material.LEATHER, Material.LEATHER, Material.LEATHER),
	MILK_BUCKET(RecuperationType.COW, SectionsType.OVER_WORLD, SubSection.OTHER,1, Material.BUCKET),
	CLAY_BALL(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.OTHER,1),
	BRICK_ITEM(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.OTHER,1, Material.CLAY_BALL),
	BRICKS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, BRICK_ITEM, BRICK_ITEM, BRICK_ITEM),
	BRICK_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,4, BRICKS, BRICKS, BRICKS, BRICKS, BRICKS, BRICKS),
	BRICKS_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, BRICK_ITEM, BRICK_ITEM, BRICK_ITEM),
	CLAY_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, CLAY_BALL, CLAY_BALL, CLAY_BALL, CLAY_BALL),
	HARDENED_CLAY(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.COLORED,1, Material.CLAY_BLOCK),
	SUGAR_CANES(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.VEGETAL,1),
	PAPER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,3, Material.SUGAR_CANES, Material.SUGAR_CANES, Material.SUGAR_CANES),
	BOOK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.PAPER, Material.PAPER, Material.PAPER, Material.LEATHER),
	ENCHANTMENT_TABLE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN,DIAMOND, DIAMOND, BOOK),
	BOOKSHELF(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.VEGETAL, 1, RANDOM_WOOK_PLANKS,RANDOM_WOOK_PLANKS,RANDOM_WOOK_PLANKS,RANDOM_WOOK_PLANKS,RANDOM_WOOK_PLANKS,RANDOM_WOOK_PLANKS,BOOK, BOOK, BOOK),
	SLIME_BALL(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	STICKY_PISTON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE, 1, SLIME_BALL, PISTON),
	MINECART_CHEST(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.CHEST, Material.MINECART),
	MINECART_FURNACE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.FURNACE, Material.MINECART),
	EGG(RecuperationType.CHICKEN, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	COMPASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.REDSTONE),
	FISHING_ROD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.STRING, Material.STRING, Material.STICK, Material.STICK, Material.STICK),
	CLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.GOLD_INGOT, Material.REDSTONE),
	GLOWSTONE_DUST(RecuperationType.MINE, SectionsType.NETHER, SubSection.OTHER,1),
	GLOWSTONE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 1, GLOWSTONE_DUST, GLOWSTONE_DUST, GLOWSTONE_DUST, GLOWSTONE_DUST),
	REDSTONE_LAMP(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, REDSTONE, REDSTONE, REDSTONE, REDSTONE, GLOWSTONE),
	FISH(RecuperationType.FISHING, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	SALMON(RecuperationType.FISHING, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	CLOWNFISH(RecuperationType.FISHING, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	PUFFERFISH(RecuperationType.FISHING, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_FISH(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.FOOD,1, Material.FISH),
	COOKED_SALMON(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.FOOD,1, Material.SALMON),
	BONE(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS, 1),
	INK_SAC_DYE(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	ROSE_RED_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.POPPY),
	CACTUS_GREEN_DYE(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.COLORED,1, Material.CACTUS),
	CACAO_BEENS_DYE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	BONE_MEAL_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.BONE),
	LAPIS_LAZULI_DYE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.COLORED,1),
	LAPIS_LAZULI_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES, 1, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE, Material.LAPIS_LAZULI_DYE),
	PURPLE_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,2, Material.LAPIS_LAZULI_DYE, Material.ROSE_RED_DYE),
	CYAN_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,2, Material.LAPIS_LAZULI_DYE, Material.CACTUS_GREEN_DYE),
	LIGHT_GRAY_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 3, Material.BONE_MEAL_DYE, Material.BONE_MEAL_DYE, Material.INK_SAC_DYE),
	GRAY_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,2, Material.INK_SAC_DYE, Material.BONE_MEAL_DYE),
	PINK_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.PINK_TULIP),
	LIME_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,2, Material.CACTUS_GREEN_DYE, Material.BONE_MEAL_DYE),
	YELLOW_DANDELION_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.DANDELION),
	LIGHT_BLUE_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.BLUE_ORCHID),
	MAGENTA_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.ALLIUM),
	ORANGE_DYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.ORANGE_TULIP),
	ORANGE_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, ORANGE_DYE),
	MAGENTA_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, MAGENTA_DYE),
	LIGHT_BLUE_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, LIGHT_BLUE_DYE),
	YELLOW_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, DANDELION),
	LIME_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, LIME_DYE),
	PINK_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, PINK_DYE),
	GRAY_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, GRAY_DYE),
	LIGHT_GRAY_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, LIGHT_GRAY_DYE),
	CYAN_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, CYAN_DYE),
	PURPLE_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, PURPLE_DYE),
	BLUE_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, LAPIS_LAZULI_DYE),
	BROWN_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, CACAO_BEENS_DYE),
	GREEN_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, CACTUS_GREEN_DYE),
	RED_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, ROSE_RED_DYE),
	BLACK_WOOL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, WOOL, INK_SAC_DYE),
	WHITE_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.WOOL, Material.WOOL),
	ORANGE_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.ORANGE_WOOL, Material.ORANGE_WOOL),
	MAGENTA_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL),
	LIGHT_BLUE_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL),
	YELLOW_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.YELLOW_WOOL, Material.YELLOW_WOOL),
	LIME_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.LIME_WOOL, Material.LIME_WOOL),
	PINK_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.PINK_WOOL, Material.PINK_WOOL),
	LIGHT_GRAY_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL),
	CYAN_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.CYAN_WOOL, Material.CYAN_WOOL),
	PURPLE_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.PURPLE_WOOL, Material.PURPLE_WOOL),
	BLUE_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.BLUE_WOOL, Material.BLUE_WOOL),
	GREEN_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.GREEN_WOOL, Material.GREEN_WOOL),
	RED_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.RED_WOOL, Material.RED_WOOL),
	BLACK_CARPET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,3, Material.BLACK_WOOL, Material.BLACK_WOOL),
	WHITE_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, BONE_MEAL_DYE),
	ORANGE_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, ORANGE_DYE),
	MAGENTA_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, MAGENTA_DYE),
	LIGHT_BLUE_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, LIGHT_BLUE_DYE),
	YELLOW_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, YELLOW_DANDELION_DYE),
	LIME_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, LIME_DYE),
	PINK_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, PINK_DYE),
	GRAY_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8,GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GRAY_DYE),
	LIGHT_GRAY_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, LIGHT_GRAY_DYE),
	CYAN_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, CYAN_DYE),
	PURPLE_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, PURPLE_DYE),
	BLUE_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, LAPIS_LAZULI_DYE),
	BROWN_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, CACAO_BEENS_DYE),
	GREEN_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, CACTUS_GREEN_DYE),
	RED_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, ROSE_RED_DYE),
	BLACK_STAINED_GLASS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, GLASS, INK_SAC_DYE),
	WHITE_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.BONE_MEAL_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	ORANGE_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.ORANGE_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	MAGENTA_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.MAGENTA_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	LIGHT_BLUE_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.LIGHT_BLUE_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	YELLOW_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.YELLOW_DANDELION_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	LIME_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.LIME_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	PINK_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.PINK_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	GRAY_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.GRAY_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	LIGHT_GRAY_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.LIGHT_GRAY_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	CYAN_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.CYAN_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	PURPLE_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.PURPLE_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	BLUE_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.LAPIS_LAZULI_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	BROWN_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.CACAO_BEENS_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	GREEN_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.CACTUS_GREEN_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	RED_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.ROSE_RED_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	BLACK_HARDENED_CLAY(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,8, Material.INK_SAC_DYE, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY, Material.HARDENED_CLAY),
	WHITE_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.WHITE_STAINED_GLASS, Material.WHITE_STAINED_GLASS, Material.WHITE_STAINED_GLASS, Material.WHITE_STAINED_GLASS, Material.WHITE_STAINED_GLASS, Material.WHITE_STAINED_GLASS),
	ORANGE_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.ORANGE_STAINED_GLASS, Material.ORANGE_STAINED_GLASS, Material.ORANGE_STAINED_GLASS, Material.ORANGE_STAINED_GLASS, Material.ORANGE_STAINED_GLASS, Material.ORANGE_STAINED_GLASS),
	MAGENTA_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.MAGENTA_STAINED_GLASS, Material.MAGENTA_STAINED_GLASS, Material.MAGENTA_STAINED_GLASS, Material.MAGENTA_STAINED_GLASS, Material.MAGENTA_STAINED_GLASS, Material.MAGENTA_STAINED_GLASS),
	LIGHT_BLUE_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.LIGHT_BLUE_STAINED_GLASS, Material.LIGHT_BLUE_STAINED_GLASS, Material.LIGHT_BLUE_STAINED_GLASS, Material.LIGHT_BLUE_STAINED_GLASS, Material.LIGHT_BLUE_STAINED_GLASS, Material.LIGHT_BLUE_STAINED_GLASS),
	YELLOW_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.YELLOW_STAINED_GLASS, Material.YELLOW_STAINED_GLASS, Material.YELLOW_STAINED_GLASS, Material.YELLOW_STAINED_GLASS, Material.YELLOW_STAINED_GLASS, Material.YELLOW_STAINED_GLASS),
	LIME_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.LIME_STAINED_GLASS, Material.LIME_STAINED_GLASS, Material.LIME_STAINED_GLASS, Material.LIME_STAINED_GLASS, Material.LIME_STAINED_GLASS, Material.LIME_STAINED_GLASS),
	PINK_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.PINK_STAINED_GLASS, Material.PINK_STAINED_GLASS, Material.PINK_STAINED_GLASS, Material.PINK_STAINED_GLASS, Material.PINK_STAINED_GLASS, Material.PINK_STAINED_GLASS),
	GRAY_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS),
	LIGHT_GRAY_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.LIGHT_GRAY_STAINED_GLASS, Material.LIGHT_GRAY_STAINED_GLASS, Material.LIGHT_GRAY_STAINED_GLASS, Material.LIGHT_GRAY_STAINED_GLASS, Material.LIGHT_GRAY_STAINED_GLASS, Material.LIGHT_GRAY_STAINED_GLASS),
	CYAN_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.CYAN_STAINED_GLASS, Material.CYAN_STAINED_GLASS, Material.CYAN_STAINED_GLASS, Material.CYAN_STAINED_GLASS, Material.CYAN_STAINED_GLASS, Material.CYAN_STAINED_GLASS),
	PURPLE_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.PURPLE_STAINED_GLASS, Material.PURPLE_STAINED_GLASS, Material.PURPLE_STAINED_GLASS, Material.PURPLE_STAINED_GLASS, Material.PURPLE_STAINED_GLASS, Material.PURPLE_STAINED_GLASS),
	BLUE_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.BLUE_STAINED_GLASS, Material.BLUE_STAINED_GLASS, Material.BLUE_STAINED_GLASS, Material.BLUE_STAINED_GLASS, Material.BLUE_STAINED_GLASS, Material.BLUE_STAINED_GLASS),
	BROWN_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.BROWN_STAINED_GLASS, Material.BROWN_STAINED_GLASS, Material.BROWN_STAINED_GLASS, Material.BROWN_STAINED_GLASS, Material.BROWN_STAINED_GLASS, Material.BROWN_STAINED_GLASS),
	GREEN_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.GREEN_STAINED_GLASS, Material.GREEN_STAINED_GLASS, Material.GREEN_STAINED_GLASS, Material.GREEN_STAINED_GLASS, Material.GREEN_STAINED_GLASS, Material.GREEN_STAINED_GLASS),
	RED_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.RED_STAINED_GLASS, Material.RED_STAINED_GLASS, Material.RED_STAINED_GLASS, Material.RED_STAINED_GLASS, Material.RED_STAINED_GLASS, Material.RED_STAINED_GLASS),
	BLACK_STAINED_GLASS_PANE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,16, Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS),
	SUGAR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.SUGAR_CANES),
	CAKE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.WHEAT, Material.WHEAT, Material.WHEAT, Material.EGG, Material.SUGAR, Material.SUGAR, Material.MILK_BUCKET, Material.MILK_BUCKET, Material.MILK_BUCKET),
	BED(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, Material.WOOL, Material.WOOL, Material.WOOL, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS, Material.RANDOM_WOOK_PLANKS),
	REPEATER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.STONE, Material.STONE, Material.STONE, Material.REDSTONE_TORCH, Material.REDSTONE_TORCH, Material.REDSTONE),
	SHEARS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.IRON_INGOT, Material.IRON_INGOT),
	PUMPKIN_SEEDS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,4, Material.PUMPKIN),
	MELON_SLICE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	MELON_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD, 1, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE, MELON_SLICE),
	MELON_SEEDS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,4, Material.MELON_SLICE),
	RAW_BEEF(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_BEEF(RecuperationType.FURNACE, SectionsType.OVER_WORLD, SubSection.FOOD,1, Material.RAW_BEEF),
	RAW_CHICKEN(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_CHICKEN(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.FOOD,1, Material.RAW_CHICKEN),
	ROTTEN_FLESH(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	ENDER_PEARL(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	BLAZE_ROD(RecuperationType.DROP_MOB, SectionsType.NETHER, SubSection.MOBS_DROPS,1),
	GHAST_TEAR(RecuperationType.DROP_MOB, SectionsType.NETHER, SubSection.MOBS_DROPS,1),
	GOLD_NUGGET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,9, Material.GOLD_INGOT),
	NETHER_WART(RecuperationType.MINE, SectionsType.NETHER, SubSection.OTHER,1),
	GLASS_BOTTLE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,3, Material.GLASS, Material.GLASS, Material.GLASS),
	WATER_BOTTLE(RecuperationType.WATER, SectionsType.OTHER, SubSection.OTHER,1, Material.GLASS_BOTTLE),
	SPIDER_EYE(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	FERMENTED_SPIDER_EYE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.SPIDER_EYE, Material.MUSHROOM_BROWN, Material.SUGAR),
	BLAZE_POWDER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.MOBS_DROPS,2, Material.BLAZE_ROD),
	MAGMA_CREAM(RecuperationType.DROP_MOB, SectionsType.NETHER, SubSection.MOBS_DROPS,1),
	BREWING_STAND(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.BLAZE_ROD, Material.COBBLESTONE, Material.COBBLESTONE, Material.COBBLESTONE),
	CAULDRON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT, Material.IRON_INGOT),
	EYE_OF_ENDER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.BLAZE_POWDER, Material.ENDER_PEARL),
	ENDER_CHEST(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, EYE_OF_ENDER, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN),
	GLISTERING_MELON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.MELON_SLICE, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET),
	BOTTLE_OF_ENCHANTING(RecuperationType.MISCELLANEOUS, SectionsType.OVER_WORLD, SubSection.OTHER,1),
	FIRE_CHARGE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,3, Material.GUNPOWDER, Material.COAL, Material.BLAZE_POWDER),
	BOOK_AND_QUILL(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.INK_SAC_DYE, Material.FEATHER, Material.BOOK),
	WRITTEN_BOOK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.BOOKSHELF),
	EMERALD(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.ORES,1),
	EMERALD_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,9, EMERALD, EMERALD, EMERALD, EMERALD, EMERALD, EMERALD, EMERALD, EMERALD, EMERALD),
	ITEM_FRAME(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.LEATHER, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK),
	FLOWER_POT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.BRICK_ITEM, Material.BRICK_ITEM, Material.BRICK_ITEM),
	CARROT(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	POTATO_POISONOUS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	POTATO(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	POTATO_BAKED(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.FOOD,1, Material.POTATO),
	MAP(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.PAPER, Material.PAPER, Material.PAPER, Material.PAPER, Material.PAPER, Material.PAPER, Material.PAPER, Material.PAPER, Material.COMPASS),
	MAP_FILLED(RecuperationType.USE, SectionsType.OTHER, SubSection.OTHER,1, Material.MAP),
	GOLDEN_CARROT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.CARROT, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET, Material.GOLD_NUGGET),
	SKELETON_SKULL(RecuperationType.MISCELLANEOUS, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	WITHER_SKELETON_HEAD(RecuperationType.DROP_MOB, SectionsType.NETHER, SubSection.MOBS_DROPS,1),
	ZOMBIE_HEAD(RecuperationType.MISCELLANEOUS, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	STEVE_HEAD(RecuperationType.MISCELLANEOUS, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	CREEPER_HEAD(RecuperationType.MISCELLANEOUS, SectionsType.OVER_WORLD, SubSection.MOBS_DROPS,1),
	CARROT_ON_A_STICK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.TOOLS,1, Material.CARROT, Material.FISHING_ROD),
	NETHER_STAR(RecuperationType.DROP_MOB, SectionsType.OTHER, SubSection.MOBS_DROPS,1),
	BEACON(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, OBSIDIAN, OBSIDIAN, OBSIDIAN, GLASS, GLASS, GLASS, GLASS, GLASS, NETHER_STAR),
	PUMPKIN_PIE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.PUMPKIN, Material.EGG, Material.SUGAR),
	FIREWORK_ROCKET(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.GUNPOWDER, Material.PAPER),
	FIREWORD_STAR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.GUNPOWDER, Material.LAPIS_LAZULI_DYE),
	ENCHANTED_BOOK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1),
	NETHER_BRICK(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.BLOCKS,1, Material.NETHERRACK),
	NETHER_BRICK_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,1, NETHER_BRICK, NETHER_BRICK, NETHER_BRICK, NETHER_BRICK),
	NETHER_BRICK_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS, 6, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK),
	NETHER_BRICK_FENCE(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,6, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK),
	NETHER_BRICK_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.BLOCKS,4, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK, NETHER_BRICK_BLOCK),
	QUARTZ(RecuperationType.MINE, SectionsType.NETHER, SubSection.BLOCKS,1),
	REDSTONE_COMPARATOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.QUARTZ, Material.REDSTONE_TORCH, Material.REDSTONE_TORCH, Material.REDSTONE_TORCH, Material.STONE, Material.STONE, Material.STONE),
	QUARTZ_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,1, Material.QUARTZ, Material.QUARTZ, Material.QUARTZ, Material.QUARTZ),
	QUARTZ_SLAB(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES, 6, QUARTZ_BLOCK, QUARTZ_BLOCK, QUARTZ_BLOCK),
	CHISELED_QUARTZ_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,1, Material.QUARTZ_SLAB, Material.QUARTZ_SLAB),
	PILLAR_QUARTZ_BLOCK(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,2, Material.QUARTZ, Material.QUARTZ),
	QUARTZ_STAIRS(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.ORES,4, Material.QUARTZ, Material.QUARTZ, Material.QUARTZ, Material.QUARTZ),
	DAYLIGHT_SENSOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.GLASS, Material.GLASS, Material.GLASS, Material.QUARTZ, Material.QUARTZ, Material.QUARTZ, Material.RANDOM_WOOD_SLAB, Material.RANDOM_WOOD_SLAB, Material.RANDOM_WOOD_SLAB),
	MINECART_WITH_TNT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.MINECART, Material.TNT),
	MINECART_WITH_HOPPER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.REDSTONE,1, Material.MINECART, Material.HOPPER),
	PRISMARINE_SHARD(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.UNDER_WATER_TEMPLE,1),
	PRISMARINE_CRYSTAL(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.UNDER_WATER_TEMPLE,1),
	PRISMARINE_BRICKS(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.UNDER_WATER_TEMPLE,1, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD),
	DARK_PRISMARINE(RecuperationType.MINE, SectionsType.OVER_WORLD, SubSection.UNDER_WATER_TEMPLE,1, Material.INK_SAC_DYE, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD),
	SEA_LANTERN(RecuperationType.MINE_SILK_TOUCH, SectionsType.OVER_WORLD, SubSection.UNDER_WATER_TEMPLE,1, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_SHARD, Material.PRISMARINE_CRYSTAL, Material.PRISMARINE_CRYSTAL, Material.PRISMARINE_CRYSTAL, Material.PRISMARINE_CRYSTAL, Material.PRISMARINE_CRYSTAL),
	RAW_RABBIT(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_RABBIT(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.FOOD,1, Material.RAW_RABBIT),
	STEW_STEW_RABBIT(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.FOOD,1, Material.CARROT, Material.MUSHROOM_BROWN, Material.BOWL, Material.POTATO_BAKED, Material.COOKED_RABBIT),
	FOOT_RABBIT(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	RABBIT_HIDE(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	ARMOR_STAND(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STICK, Material.STONE_SLAB),
	IRON_ARMOR_HORSE(RecuperationType.DUNGEON, SectionsType.NETHER, SubSection.LUCK,1),
	GOLD_ARMOR_HORSE(RecuperationType.DUNGEON, SectionsType.NETHER, SubSection.LUCK,1),
	LEAD(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.OTHER,1, Material.STRING, Material.STRING, Material.STRING, Material.STRING, Material.SLIME_BALL),
	NAMETAG(RecuperationType.DUNGEON, SectionsType.NETHER, SubSection.LUCK,1),
	RAW_MUTTON(RecuperationType.DROP_MOB, SectionsType.OVER_WORLD, SubSection.FOOD,1),
	COOKED_MUTTON(RecuperationType.FURNACE, SectionsType.OTHER, SubSection.FOOD,1, Material.RAW_MUTTON),
	BLACK_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.BLACK_WOOL, Material.BLACK_WOOL, Material.BLACK_WOOL, Material.BLACK_WOOL, Material.BLACK_WOOL, Material.BLACK_WOOL),
	RED_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.RED_WOOL, Material.RED_WOOL, Material.RED_WOOL, Material.RED_WOOL, Material.RED_WOOL, Material.RED_WOOL),
	GREEN_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.GREEN_WOOL, Material.GREEN_WOOL, Material.GREEN_WOOL, Material.GREEN_WOOL, Material.GREEN_WOOL, Material.GREEN_WOOL),
	BROWN_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.BROWN_WOOL, Material.BROWN_WOOL, Material.BROWN_WOOL, Material.BROWN_WOOL, Material.BROWN_WOOL, Material.BROWN_WOOL),
	BLUE_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.BLUE_WOOL, Material.BLUE_WOOL, Material.BLUE_WOOL, Material.BLUE_WOOL, Material.BLUE_WOOL, Material.BLUE_WOOL),
	PURPLE_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.PURPLE_WOOL, Material.PURPLE_WOOL, Material.PURPLE_WOOL, Material.PURPLE_WOOL, Material.PURPLE_WOOL, Material.PURPLE_WOOL),
	CYAN_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.CYAN_WOOL, Material.CYAN_WOOL, Material.CYAN_WOOL, Material.CYAN_WOOL, Material.CYAN_WOOL, Material.CYAN_WOOL),
	LIGHT_GRAY_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL, Material.LIGHT_GRAY_WOOL),
	GRAY_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.GRAY_WOOL, Material.GRAY_WOOL, Material.GRAY_WOOL, Material.GRAY_WOOL, Material.GRAY_WOOL, Material.GRAY_WOOL),
	PINK_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.PINK_WOOL, Material.PINK_WOOL, Material.PINK_WOOL, Material.PINK_WOOL, Material.PINK_WOOL, Material.PINK_WOOL),
	LIME_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.LIME_WOOL, Material.LIME_WOOL, Material.LIME_WOOL, Material.LIME_WOOL, Material.LIME_WOOL, Material.LIME_WOOL),
	YELLOW_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.YELLOW_WOOL, Material.YELLOW_WOOL, Material.YELLOW_WOOL, Material.YELLOW_WOOL, Material.YELLOW_WOOL, Material.YELLOW_WOOL),
	LIGHT_BLUE_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL, Material.LIGHT_BLUE_WOOL),
	MAGENTA_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL, Material.MAGENTA_WOOL),
	ORANGE_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED,1, Material.STICK, Material.ORANGE_WOOL, Material.ORANGE_WOOL, Material.ORANGE_WOOL, Material.ORANGE_WOOL, Material.ORANGE_WOOL, Material.ORANGE_WOOL),
	WHITE_BANNER(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.COLORED, 1, Material.STICK, Material.WOOL, Material.WOOL, Material.WOOL, Material.WOOL, Material.WOOL, Material.WOOL),
	SPRUCE_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS, Material.SPRUCE_WOOD_PLANKS),
	BIRCH_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS, Material.BIRCH_WOOD_PLANKS),
	JUNGLE_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS, Material.JUNGLE_WOOD_PLANKS),
	ACACIA_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS, Material.ACACIA_WOOD_PLANKS),
	DARK_OAK_DOOR(RecuperationType.CRAFTING, SectionsType.OTHER, SubSection.WOOD, 1, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS, Material.DARK_OAK_WOOD_PLANKS),
	MUSIC_DISC_13(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_CAT(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_BLOCKS(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_CHIRP(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_FAR(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_MALL(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_MELLOHI(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_STAL(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_STRAD(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_WARD(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_11(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK,1),
	MUSIC_DISC_WAIT(RecuperationType.DUNGEON, SectionsType.OVER_WORLD, SubSection.LUCK, 1);

	private final RecuperationType recuperationType;
	private final SectionsType sectionType;
	private final SubSection subSection;
	private final Material[] decraftableItems;
	private final int itemsCreated;

	private Material(final RecuperationType recuperationType, final SectionsType sectionType,
			final SubSection subSection, final int itemsCreated, final Material... materials) {
		this.recuperationType = recuperationType;
		this.sectionType = sectionType;
		this.subSection = subSection;
		this.decraftableItems = materials;
		this.itemsCreated = itemsCreated;
	}

	@Override
	public final String toString() {
		return (this.name().substring(0, 1).toUpperCase() + this.name().substring(1).toLowerCase()).replace("_", " ");
	}

	public final RecuperationType getRecuperationType() {
		return this.recuperationType;
	}

	public final SectionsType getSectionType() {
		return this.sectionType;
	}

	public final SubSection getSubsection() {
		return this.subSection;
	}

	public Material[] getDecraftableItems() {
		return this.decraftableItems;
	}

	public int getItemsCreated() {
		return this.itemsCreated;
	}

}
